// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: authors.sql

package sqlc

import (
	"context"
	"errors"
)

const addCashflow = `-- name: AddCashflow :one
  insert into cashflow(
      id,name
  )select id,name from cashflow as c
  where c.id = $1
  returning id
`

var dynaAddCashflow = map[string]string{}

func init() {
	dynaAddCashflow = getDynamicQuery(addCashflow)
}

func (q *Queries) AddCashflow(ctx context.Context, dynaTable string, id int64) (int64, error) {
	tb, found := dynaAddCashflow[dynaTable]
	if !found {
		return 0, errors.New("Table " + dynaTable + "! not found.")
	}

	row := q.db.QueryRowContext(ctx, tb, id)
	err := row.Scan(&id)
	return id, err
}

const paidDelete = `-- name: PaidDelete :exec
WITH cte_paid_delete as (
  delete from cash_inex as cold
  WHERE 
    cold.id = $2
  returning cold.total
)
update ref_table as cnew set
  total = total + cte_paid_delete.total,
  name = $1
from cte_paid_delete 
where 
  cnew.id = cte_paid_delete.credit_ref
`

var dynaPaidDelete = map[string]string{}

func init() {
	dynaPaidDelete = getDynamicQuery(paidDelete)
}

type PaidDeleteParams struct {
	Name      string `json:"name"`
	InExDocID int64  `json:"in_ex_doc_id"`
}

func (q *Queries) PaidDelete(ctx context.Context, dynaTable string, arg PaidDeleteParams) error {
	tb, found := dynaPaidDelete[dynaTable]
	if !found {
		return errors.New("Table " + dynaTable + "! not found.")
	}

	_, err := q.db.ExecContext(ctx, tb, arg.Name, arg.InExDocID)
	return err
}
