// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: authors.sql

package sqlc

import (
	"context"
	"errors"
)

type AddCashflowTbGuard struct {
	Cashflow   string
	ToCashflow string
}

func getAddCashflowQuery(tb AddCashflowTbGuard) (string, error) {
	if !to_cashflowGuard[tb.ToCashflow] ||
		!cashflowGuard[tb.Cashflow] {
		return "", errors.New(tb.ToCashflow + ", " + tb.Cashflow + " !not allow.")
	}

	return `
  insert into ` + tb.Cashflow + `(
      id,name 
  )select id,name from ` + tb.ToCashflow + ` as c
  where c.id = $1
  returning id as newID
`, nil
}

func (q *Queries) AddCashflow(ctx context.Context, dynaTable AddCashflowTbGuard, id int64) (int64, error) {
	dynaQuery, errQuery := getAddCashflowQuery(dynaTable)
	if errQuery != nil {
		return 0, errQuery
	}

	row := q.db.QueryRowContext(ctx, dynaQuery, id)
	var newid int64
	err := row.Scan(&newid)
	return newid, err
}

const authDeleteIncome = `-- name: AuthDeleteIncome :exec
delete from income where 
id = $1 and name = $2
`

type AuthDeleteIncomeParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) AuthDeleteIncome(ctx context.Context, arg AuthDeleteIncomeParams) error {
	_, err := q.db.ExecContext(ctx, authDeleteIncome, arg.ID, arg.Name)
	return err
}

type FlushCashflowTbGuard struct {
	Cashflow string
}

func getFlushCashflowQuery(tb FlushCashflowTbGuard) (string, error) {
	if !cashflowGuard[tb.Cashflow] {
		return "", errors.New(tb.Cashflow + " !not allow.")
	}

	return `
  delete from  ` + tb.Cashflow + `
  where c.id = 123 
`, nil
}

func (q *Queries) FlushCashflow(ctx context.Context, dynaTable FlushCashflowTbGuard) error {
	dynaQuery, errQuery := getFlushCashflowQuery(dynaTable)
	if errQuery != nil {
		return errQuery
	}

	_, err := q.db.ExecContext(ctx, dynaQuery)
	return err
}

type PaidDeleteTbGuard struct {
	CashInex string
	RefCash  string
}

func getPaidDeleteQuery(tb PaidDeleteTbGuard) (string, error) {
	if !cash_inexGuard[tb.CashInex] ||
		!ref_cashGuard[tb.RefCash] {
		return "", errors.New(tb.CashInex + ", " + tb.RefCash + " !not allow.")
	}

	return `
WITH cte_paid_delete as (
  delete from ` + tb.CashInex + ` as cold
  WHERE 
    cold.id = $2
  returning cold.total
)
update ` + tb.RefCash + ` as cnew set
  total = total + cte_paid_delete.total,
  name = $1
from cte_paid_delete 
where 
  cnew.id = cte_paid_delete.credit_ref
`, nil
}

type PaidDeleteParams struct {
	Name      string `json:"name"`
	InExDocID int64  `json:"in_ex_doc_id"`
}

func (q *Queries) PaidDelete(ctx context.Context, dynaTable PaidDeleteTbGuard, arg PaidDeleteParams) error {
	dynaQuery, errQuery := getPaidDeleteQuery(dynaTable)
	if errQuery != nil {
		return errQuery
	}

	_, err := q.db.ExecContext(ctx, dynaQuery, arg.Name, arg.InExDocID)
	return err
}
