// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: cash.sql

package sqlc

import (
	"context"
	"errors"
)

type GetCashflowTbGuard struct {
	Cashflow string
}

func getGetCashflowQuery(tb GetCashflowTbGuard) (string, error) {
	if !cashflowGuard[tb.Cashflow] {
		return "", errors.New(tb.Cashflow + " !not allow.")
	}

	return `
select id, name, credit_ref, total from ` + tb.Cashflow + ` 
where id = $1 and name = $2
`, nil
}

type GetCashflowParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetCashflow(ctx context.Context, dynaTable GetCashflowTbGuard, arg GetCashflowParams) ([]Cashflow, error) {
	dynaQuery, errQuery := getGetCashflowQuery(dynaTable)
	if errQuery != nil {
		return nil, errQuery
	}

	rows, err := q.db.QueryContext(ctx, dynaQuery, arg.ID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cashflow{}
	for rows.Next() {
		var i Cashflow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreditRef,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
