// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: cash.sql

package sqlc

import (
	"context"
	"errors"
)

const getCashflow = `-- name: GetCashflow :many
select id, name, credit_ref, total from cashflow 
where id = $1 and name = $2
`

var dynaGetCashflow = map[string]string{}

func init() {
	dynaGetCashflow = getDynamicQuery(getCashflow)
}

type GetCashflowParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetCashflow(ctx context.Context, dynaTable string, arg GetCashflowParams) ([]Cashflow, error) {
	tb, found := dynaGetCashflow[dynaTable]
	if !found {
		return nil, errors.New("Table " + dynaTable + "! not found.")
	}

	rows, err := q.db.QueryContext(ctx, tb, arg.ID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cashflow{}
	for rows.Next() {
		var i Cashflow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreditRef,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
