// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: credit.sql

package sqlc

import (
	"context"
	"errors"
)

type GetCashCreditTbGuard struct {
	CashCredit string
}

func getGetCashCreditQuery(tb GetCashCreditTbGuard) (string, error) {
	if !cash_creditGuard[tb.CashCredit] {
		return "", errors.New(tb.CashCredit + " !not allow.")
	}

	return `
select id, name, credit_ref, total from ` + tb.CashCredit + `
where id = $1 and name = $2
limit 1
`, nil
}

type GetCashCreditParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetCashCredit(ctx context.Context, dynaTable GetCashCreditTbGuard, arg GetCashCreditParams) (CashCredit, error) {
	dynaQuery, errQuery := getGetCashCreditQuery(dynaTable)
	if errQuery != nil {
		return CashCredit{}, errQuery
	}

	row := q.db.QueryRowContext(ctx, dynaQuery, arg.ID, arg.Name)
	var i CashCredit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreditRef,
		&i.Total,
	)
	return i, err
}
