// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: credit.sql

package sqlc

import (
	"context"
	"errors"
)

const getCashCredit = `-- name: GetCashCredit :one
select id, name, credit_ref, total from cash_credit
where id = $1 and name = $2
limit 1
`

var dynaGetCashCredit = map[string]string{}

func init() {
	dynaGetCashCredit = getDynamicQuery(getCashCredit)
}

type GetCashCreditParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetCashCredit(ctx context.Context, dynaTable string, arg GetCashCreditParams) (CashCredit, error) {
	tb, found := dynaGetCashCredit[dynaTable]
	if !found {
		return CashCredit{}, errors.New("Table " + dynaTable + "! not found.")
	}

	row := q.db.QueryRowContext(ctx, tb, arg.ID, arg.Name)
	var i CashCredit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreditRef,
		&i.Total,
	)
	return i, err
}
