// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: income.sql

package sqlc

import (
	"context"
)

const deleteCashIncome = `-- name: DeleteCashIncome :exec
delete from income where 
id = $1 and name = $2
`

type DeleteCashIncomeParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) DeleteCashIncome(ctx context.Context, arg DeleteCashIncomeParams) error {
	_, err := q.db.ExecContext(ctx, deleteCashIncome, arg.ID, arg.Name)
	return err
}

const getCashIncome = `-- name: GetCashIncome :many
select id, name, credit_ref, total from income
where id = $1 and name = $2
`

type GetCashIncomeParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetCashIncome(ctx context.Context, arg GetCashIncomeParams) ([]Income, error) {
	rows, err := q.db.QueryContext(ctx, getCashIncome, arg.ID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Income{}
	for rows.Next() {
		var i Income
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreditRef,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
