// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc

import (
	"database/sql"
)

type CashCredit struct {
	ID        int64         `json:"id"`
	Name      string        `json:"name"`
	CreditRef sql.NullInt64 `json:"credit_ref"`
	Total     string        `json:"total"`
}

type CashInex struct {
	ID        int64         `json:"id"`
	Name      string        `json:"name"`
	CreditRef sql.NullInt64 `json:"credit_ref"`
	Total     string        `json:"total"`
}

type Cashflow struct {
	ID        int64         `json:"id"`
	Name      string        `json:"name"`
	CreditRef sql.NullInt64 `json:"credit_ref"`
	Total     string        `json:"total"`
}

type Income struct {
	ID        int64         `json:"id"`
	Name      string        `json:"name"`
	CreditRef sql.NullInt64 `json:"credit_ref"`
	Total     string        `json:"total"`
}

type RefTable struct {
	ID        int64         `json:"id"`
	Name      string        `json:"name"`
	CreditRef sql.NullInt64 `json:"credit_ref"`
	Total     string        `json:"total"`
}
